//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZagaZaga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_account
    {
        public int id { get; set; }
        public string bank_name { get; set; }
        public string country { get; set; }
        public string username { get; set; }
        public string userpass { get; set; }
        public string email { get; set; }
        public string pass { get; set; }
        public string balance { get; set; }
        public string account_number { get; set; }
        public string routine_number { get; set; }
        public string price { get; set; }
    }
}
