//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZagaZaga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buy
    {
        public int id { get; set; }
        public string u_name { get; set; }
        public string email { get; set; }
        public string p_id { get; set; }
        public string p_name { get; set; }
        public string info { get; set; }
        public string login { get; set; }
        public string pass { get; set; }
    }
}
