//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZagaZaga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int MessageID { get; set; }
        public string MessageBody { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> TicketID { get; set; }
        public string SentDate { get; set; }
        public string SentBy { get; set; }
    }
}
