//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZagaZaga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class check_req
    {
        public int id { get; set; }
        public Nullable<int> u_id { get; set; }
        public string u_name { get; set; }
        public string check_type { get; set; }
        public Nullable<int> p_id { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> price { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public Nullable<int> user_amount { get; set; }
        public string status { get; set; }
    }
}
