//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZagaZaga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class credit_card
    {
        public int id { get; set; }
        public string holder_name { get; set; }
        public string card_number { get; set; }
        public string card_expiry { get; set; }
        public string online_access { get; set; }
        public string pass { get; set; }
        public string card_limit { get; set; }
        public string amount { get; set; }
        public string price { get; set; }
    }
}
