//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZagaZaga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class google_voice
    {
        public int id { get; set; }
        public string product_name { get; set; }
        public string state { get; set; }
        public string phone { get; set; }
        public string details { get; set; }
        public string email { get; set; }
        public string pass { get; set; }
        public string recovery_email { get; set; }
        public string price { get; set; }
    }
}
