//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZagaZaga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paypal_transfer
    {
        public int id { get; set; }
        public string paypal_name { get; set; }
        public string paypal_pass { get; set; }
        public string paypal_city { get; set; }
        public string paypal_state { get; set; }
        public string amount { get; set; }
        public string price { get; set; }
    }
}
