//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZagaZaga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class send_check
    {
        public int id { get; set; }
        public string client_name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip_code { get; set; }
        public string amount { get; set; }
        public string price { get; set; }
    }
}
